//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_No1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSex { get; set; }
        public string MaritalStatus { get; set; }
        public System.DateTime EmployeeDoB { get; set; }
        public string JobTitle { get; set; }
        public string IdentityCard { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string Department { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyPhoneNumber { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string EmploymentStatus { get; set; }
        public int RoleID { get; set; }
    }
}
