//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_No1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JRCHENGEntities : DbContext
    {
        public JRCHENGEntities()
            : base("name=JRCHENGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<View_Sales_Product_Partners> View_Sales_Product_Partners { get; set; }
    
        [DbFunction("JRCHENGEntities", "fnGetSalesData")]
        public virtual IQueryable<fnGetSalesData_Result> fnGetSalesData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGetSalesData_Result>("[JRCHENGEntities].[fnGetSalesData]()");
        }
    }
}
