//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_No1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> EmployeeCreate { get; set; }
        public Nullable<bool> EmployeeRetrieve { get; set; }
        public Nullable<bool> EmployeeUpdate { get; set; }
        public Nullable<bool> EmployeeDelete { get; set; }
        public Nullable<bool> SalesCreate { get; set; }
        public Nullable<bool> SalesRetrieve { get; set; }
        public Nullable<bool> SalesUpdate { get; set; }
        public Nullable<bool> SalesDelete { get; set; }
        public Nullable<bool> StockCreate { get; set; }
        public Nullable<bool> StockRetrieve { get; set; }
        public Nullable<bool> StockUpdate { get; set; }
        public Nullable<bool> StockDelete { get; set; }
        public Nullable<bool> ProcurementCreate { get; set; }
        public Nullable<bool> ProcurementRetrieve { get; set; }
        public Nullable<bool> ProcurementUpdate { get; set; }
        public Nullable<bool> ProcurementDelete { get; set; }
        public Nullable<bool> ProductCreate { get; set; }
        public Nullable<bool> ProductRetrieve { get; set; }
        public Nullable<bool> ProductUpdate { get; set; }
        public Nullable<bool> ProductDelete { get; set; }
    }
}
