//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_No1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JRCHENGEntities : DbContext
    {
        public JRCHENGEntities()
            : base("name=JRCHENGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<View_Sales_Product_Partners> View_Sales_Product_Partners { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<stock_product_view> stock_product_view { get; set; }
        public virtual DbSet<View_Products_Partners> View_Products_Partners { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    
        [DbFunction("JRCHENGEntities", "fnGetSalesData")]
        public virtual IQueryable<fnGetSalesData_Result> fnGetSalesData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGetSalesData_Result>("[JRCHENGEntities].[fnGetSalesData]()");
        }
    
        public virtual int spCreateSalesData(Nullable<int> salesPrice, Nullable<int> salesCount, Nullable<System.DateTime> salesTime, Nullable<int> productID, Nullable<int> corporateID)
        {
            var salesPriceParameter = salesPrice.HasValue ?
                new ObjectParameter("salesPrice", salesPrice) :
                new ObjectParameter("salesPrice", typeof(int));
    
            var salesCountParameter = salesCount.HasValue ?
                new ObjectParameter("salesCount", salesCount) :
                new ObjectParameter("salesCount", typeof(int));
    
            var salesTimeParameter = salesTime.HasValue ?
                new ObjectParameter("salesTime", salesTime) :
                new ObjectParameter("salesTime", typeof(System.DateTime));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var corporateIDParameter = corporateID.HasValue ?
                new ObjectParameter("corporateID", corporateID) :
                new ObjectParameter("corporateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateSalesData", salesPriceParameter, salesCountParameter, salesTimeParameter, productIDParameter, corporateIDParameter);
        }
    
        public virtual int spInsertSalesData(Nullable<int> salesPrice, Nullable<int> salesCount, Nullable<System.DateTime> salesTime, Nullable<int> productID, Nullable<int> corporateID)
        {
            var salesPriceParameter = salesPrice.HasValue ?
                new ObjectParameter("salesPrice", salesPrice) :
                new ObjectParameter("salesPrice", typeof(int));
    
            var salesCountParameter = salesCount.HasValue ?
                new ObjectParameter("salesCount", salesCount) :
                new ObjectParameter("salesCount", typeof(int));
    
            var salesTimeParameter = salesTime.HasValue ?
                new ObjectParameter("salesTime", salesTime) :
                new ObjectParameter("salesTime", typeof(System.DateTime));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var corporateIDParameter = corporateID.HasValue ?
                new ObjectParameter("corporateID", corporateID) :
                new ObjectParameter("corporateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertSalesData", salesPriceParameter, salesCountParameter, salesTimeParameter, productIDParameter, corporateIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
