//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_No1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int CorporateID { get; set; }
        public string CorporateName { get; set; }
        public string CorporatePrinciple { get; set; }
        public string CorporateDescription { get; set; }
        public string CorporateAddress { get; set; }
        public string CorporateTaxIDNo { get; set; }
        public string CorporateType { get; set; }
    }
}
