//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_No1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchasesID { get; set; }
        public int PurchasesCount { get; set; }
        public System.DateTime PurchasesTime { get; set; }
        public int FinalPrice { get; set; }
        public int ProductID { get; set; }
        public int CorporateID { get; set; }
    }
}
